
main: getcert.cpp changepw.cpp sendmsg.cpp
	g++ -Wall getcert.cpp -o getcert -lcrypto -lssl
	g++ -Wall changepw.cpp -o changepw -lcrypto -lssl
	g++ -Wall sendmsg.cpp -o sendmsg -lcrypto -lssl
	g++ -Wall recvmsg.cpp -o recvmsg -lcrypto -lssl
